# Generated by Django 4.2.2 on 2023-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_box',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
