# Generated by Django 4.2.2 on 2023-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toapp', '0002_alter_todo_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_box',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
